"""Structured OCR using Gemini 2.5 Pro JSON mode.

Extracts text + inline SVG figures from math textbook images.
Returns structured JSON with text sections and SVG code for geometric figures.
SVG figures are generated by Gemini following school geometry conventions.
"""

from __future__ import annotations

import base64
import json
import os
import re
import sys
import urllib.request

try:
    from .retry import retry_with_backoff
    from .gemini_counter import increment_gemini_counter
    from .exceptions import OCRCorrectionUnavailable
except ImportError:
    from lib.retry import retry_with_backoff
    from lib.gemini_counter import increment_gemini_counter
    from lib.exceptions import OCRCorrectionUnavailable


def ocr_structured(image_bytes: bytes, mime_type: str, source_lang: str = "ro",
                   *, timeout_s: int = 60, max_retries: int = 0,
                   key_env: str = "GOOGLE_AI_API_KEY") -> dict:
    """Extract structured content from an image using Gemini JSON mode.

    Returns dict with "title" and "sections" list.
    Section types: heading, paragraph, step, observation, list, figure, two_column.
    Figure sections have "svg" field with inline SVG code (school geometry conventions).

    S4 + R8 (audit 2026-09-07): ``timeout_s`` per-model. maxDuration REAL = 300s
    (vercel.json), nu 60s → default ridicat 45→60 (o pagină bogată de geometrie ia
    ~30-44s; 45 tăia evitabil). ``max_retries=0``: un timeout ridică imediat + cascadează
    pe modelul următor (5xx/timeout → fallback). Apelantul (``api/ocr.py`` fallback
    Azure→Gemini) trece bugetul rămas (≤120s). Lanțul complet ≪ 300s.

    ``key_env`` (Faza 4.5d, 2026-09-11): numele env var-ului cu cheia Google — implicit
    ``GOOGLE_AI_API_KEY`` (free). ``api/ocr.py`` trece ``GOOGLE_AI_API_KEY_PAID`` DOAR pt
    corectarea lucrărilor elevilor (câmpul ``tier=paid``, TestePanel.tsx) — lucrarea unui
    minor nu trece prin tier-ul free-tier, citit de oameni. ``api/translate_text.py``
    (F8) nu trimite acest parametru → rămâne pe ``GOOGLE_AI_API_KEY``, neatins.
    """
    api_key = os.environ.get(key_env, "").strip()
    if not api_key:
        raise RuntimeError(f"{key_env} not set")

    image_b64 = base64.b64encode(image_bytes).decode("utf-8")
    # Third site of the same trap (found by the requirements auditor, 08.09.2026):
    # `de` was missing while the editor's language switch offers it, so a German
    # source page went to the model described as "de" instead of "German".
    lang_names = {
        "ro": "Romanian",
        "sk": "Slovak",
        "en": "English",
        "de": "German",
    }
    src = lang_names.get(source_lang, source_lang)

    print(f"[OCR-STRUCT] Processing: {len(image_bytes)} bytes, {mime_type}, {source_lang}", file=sys.stderr)

    prompt = (
        f"Analyze this {src} math textbook page image. Return a JSON object.\n\n"
        "STRUCTURE:\n"
        '{{"title":"page title","sections":[\n'
        '  {{"type":"heading","content":"text","level":1}},\n'
        '  {{"type":"paragraph","content":"text with $LaTeX$ formulas"}},\n'
        '  {{"type":"step","content":"$P_1$: construction step text"}},\n'
        '  {{"type":"figure","bbox":{{"x":0.1,"y":0.3,"w":0.4,"h":0.2}},"caption":"optional"}},\n'
        '  {{"type":"observation","content":"observation text"}},\n'
        '  {{"type":"list","content":"1. item one\\n2. item two"}},\n'
        '  {{"type":"two_column","left":[...sections...],"right":[...sections...]}}\n'
        ']}}\n\n'

        "TEXT RULES:\n"
        "1. ALL math as LaTeX: $\\triangle ABC$, $\\angle A$, $AB = 4 \\text{{ cm}}$\n"
        "2. Construction steps (P1, P2 etc.) -> type 'step', use Unicode subscript in content\n"
        "3. Bold terms: **bold** markers\n"
        "4. Preserve EXACT text — do not summarize or skip\n"
        "5. If a word is hyphenated across a line break, join it into one word\n"
        "6. Lists: numbered (1. 2.) or lettered (a) b))\n"
        "7. IGNORE page numbers (standalone numbers like 205, 206 at edges) — do NOT include them\n"
        "8. 'Observatie.' / 'Exemplu.' / 'Definitie.' etc. MUST be bold: **Observatie.**\n\n"

        "FIGURE RULES — CRITICAL:\n"
        "7. For EVERY geometric figure/diagram, return a 'figure' section with:\n"
        "   - 'bbox': bounding box as fractions of the FULL IMAGE dimensions (0.0 to 1.0):\n"
        "     x = left_pixel / image_width,  y = top_pixel / image_height\n"
        "     w = figure_width / image_width, h = figure_height / image_height\n"
        "   - The bbox must cover ONLY that specific figure, NOT adjacent figures\n"
        "   - For figures in two_column: left-column figures have x < 0.5, right-column figures have x > 0.35\n"
        "   - Include vertex labels and measurement text inside the bbox\n"
        "   - 'caption': short description (e.g. 'Triunghi ABC')\n"
        "   Do NOT generate SVG. Return ONLY the bounding box.\n"
        "8. Each figure gets its OWN separate bbox — never share a bbox between two figures.\n"
        "9. If there is no figure, do not return a 'figure' section.\n\n"

        "LAYOUT RULES — CRITICAL:\n"
        "10. ALWAYS use type 'two_column' when ANY of these appear side-by-side on the page:\n"
        "    - A figure next to text or next to another figure\n"
        "    - Construction step P1 left + P2 right (VERY common in geometry pages)\n"
        "    - Any two elements that visually appear in columns, not stacked vertically\n"
        "    Do NOT linearize side-by-side content into sequential sections.\n"
        "    'two_column' has 'left': [...sections] and 'right': [...sections].\n"
        "    Each side can contain steps, figures, text, observations.\n"
        "11. Preserve the EXACT visual layout of the original page — vertical order AND column layout.\n\n"

        "Return ONLY valid JSON, no explanation or markdown wrapper."
    )

    contents = [{"parts": [
        {"text": prompt},
        {"inline_data": {"mime_type": mime_type, "data": image_b64}},
    ]}]

    payload = json.dumps({
        "contents": contents,
        "generationConfig": {
            "responseMimeType": "application/json",
            # temperature 0 (2026-09-07): taie variația run-to-run — fără el, aceeași
            # pagină dădea ba o reconstrucție bogată, ba un răspuns degenerat (1 paragraf).
            # OCR = extragere deterministă, nu creativitate → 0 e corect.
            "temperature": 0,
        },
    }).encode("utf-8")

    # Fallback chain: 3 modele Gemini distincte (cote RPD separate), toate
    # confirmate GRATUITE + funcționale empiric (probă directă API, 2026-08-08
    # — vezi .claude-outputs/research/). "gemini-2.5-flash-lite" (fostul tier 2)
    # a fost RETRAS de Google ("no longer available to new users", 404) — model
    # mort, nu doar depasit. "gemini-2.5-pro" (fostul tier 3) apare acum listat
    # paid-only pe pagina oficiala de prețuri — scos din lanț din precauție
    # R-COST (regulă absolută, "fără excepție"), deși apelul de test a răspuns
    # 200 cu cheia gratuită curentă (ambiguu, nu o dovadă de gratuitate).
    MODELS = ["gemini-3.6-flash", "gemini-3.5-flash-lite", "gemini-2.5-flash"]
    data = None
    # Faza 4.5e (2026-09-11): motivul fiecărui eșec, ca la epuizarea completă să
    # putem spune Cristinei DE CE, nu doar CE (E-OCR-004/005). "429" = cotă; orice
    # altceva ("blocked" finishReason, cod HTTP diferit, timeout) = tranzitoriu,
    # nu neapărat cotă. `fallback_reason` = "quota" DOAR dacă TOATE eșecurile au
    # fost 429 — un singur motiv diferit înseamnă cauză amestecată, nu cotă curată.
    fail_reasons: list[str] = []

    for model_name in MODELS:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent"
        req = urllib.request.Request(url, data=payload, headers={
            "Content-Type": "application/json",
            "x-goog-api-key": api_key,
        })
        try:
            def _call(r=req):
                with urllib.request.urlopen(r, timeout=timeout_s) as resp:
                    return json.loads(resp.read().decode("utf-8"))

            data = retry_with_backoff(_call, max_retries=max_retries, base_delay=1.0)
            increment_gemini_counter(model_name)
            # Faza 4.5d — descoperire din testul A/B OCR: un răspuns HTTP 200 cu
            # `finishReason` non-STOP/non-MAX_TOKENS (RECITATION = filtru copyright,
            # SAFETY, PROHIBITED_CONTENT) vine cu `content: {}` — FĂRĂ excepție, deci
            # ieșea din buclă ca "succes", iar parsarea de mai jos arunca KeyError
            # NEprins de niciun fallback (reprodus live pe 2 documente reale în testul
            # A/B, ambele PDF-uri germane de laborator). Verificare EXPLICITĂ înainte
            # de a ieși din buclă — nu un try/except pe KeyError, care ar masca și alte
            # bug-uri de parsare — tratată ca tranzitorie, exact ca 429/5xx.
            finish_reason = (
                (data.get("candidates") or [{}])[0].get("finishReason", "STOP")
            )
            has_parts = bool(
                (data.get("candidates") or [{}])[0].get("content", {}).get("parts")
            )
            if not has_parts and finish_reason not in ("STOP", "MAX_TOKENS"):
                print(
                    f"[OCR-STRUCT] {model_name} finishReason={finish_reason}, content gol "
                    "(filtru Google, nu eroare de rețea) — trecem la modelul următor",
                    file=sys.stderr,
                )
                fail_reasons.append(f"blocked:{finish_reason}")
                if model_name != MODELS[-1]:
                    continue
                if key_env != "GOOGLE_AI_API_KEY":
                    raise OCRCorrectionUnavailable()
                print(
                    "[OCR-STRUCT] All Gemini tiers blocked (finishReason), trying Mistral OCR fallback",
                    file=sys.stderr,
                )
                return _ocr_with_mistral_structured(
                    image_bytes, mime_type, src, timeout_s=timeout_s, fail_reasons=fail_reasons
                )
            print(f"[OCR-STRUCT] Success with {model_name}", file=sys.stderr)
            break
        except urllib.error.HTTPError as e:
            # 429 = rate-limited pe acest tier; 404 = model retras/inexistent
            # (exact ce s-a intamplat cu gemini-2.5-flash-lite); 500/502/503/529 =
            # model SUPRAÎNCĂRCAT/tranzitoriu (2026-09-07: gemini-3.6-flash întorcea
            # 503 "high demand" la ~jumătate din cereri, iar 503 NU declanșa fallback
            # → pagina eșua/degenera). În TOATE aceste cazuri încercăm tier-ul următor
            # în loc să oprim tot lanțul (503 e cel mai frecvent la ore de vârf).
            if e.code in (429, 404, 500, 502, 503, 529) and model_name != MODELS[-1]:
                print(f"[OCR-STRUCT] {model_name} HTTP {e.code}, trying next model", file=sys.stderr)
                fail_reasons.append(str(e.code))
                continue
            error_body = e.read().decode("utf-8", errors="replace")[:300]
            print(f"[OCR-STRUCT] HTTP {e.code}: {error_body}", file=sys.stderr)
            fail_reasons.append(str(e.code))
            if model_name == MODELS[-1]:
                if key_env != "GOOGLE_AI_API_KEY":
                    # Faza 4.5d: tier PLĂTIT (lucrare de elev) — Mistral OCR e un
                    # procesator free terț, exact tier-ul pe care cheia plătită
                    # trebuie să-l evite. Eșuează vizibil, nu leak silențios.
                    raise OCRCorrectionUnavailable()
                # All Gemini tiers exhausted — try Mistral OCR as last resort
                print("[OCR-STRUCT] All Gemini tiers exhausted, trying Mistral OCR fallback", file=sys.stderr)
                return _ocr_with_mistral_structured(
                    image_bytes, mime_type, src, timeout_s=timeout_s, fail_reasons=fail_reasons
                )
            raise
        except Exception as e:
            # Tranzitoriu = merită modelul următor: 5xx/429 SAU read-timeout. Log-urile
            # prod (2026-09-07) arătau `TimeoutError: read operation timed out` pe
            # gemini-3.6-flash (supraîncărcat) care NU cădea pe fallback → pagina eșua
            # degenerat (1 paragraf). Clientul n-are timeout propriu (așteaptă serverul,
            # maxDuration=300s) → e sigur să încercăm modelul următor (3.5-flash-lite = mai rapid).
            transient = (
                any(c in str(e) for c in ("429", "500", "502", "503", "529"))
                or isinstance(e, TimeoutError)
                or "timed out" in str(e).lower()
            )
            # "429" în text -> tot cotă, la fel ca HTTPError.code == 429 (retry_with_backoff
            # poate re-ridica un 429 ca eroare generică, nu doar ca HTTPError). Altfel,
            # "timeout" e categoria lui proprie (nu cotă) — vezi clasificarea fallback_reason.
            if "429" in str(e):
                fail_reasons.append("429")
            elif isinstance(e, TimeoutError) or "timed out" in str(e).lower():
                fail_reasons.append("timeout")
            else:
                fail_reasons.append("error")
            if transient and model_name != MODELS[-1]:
                print(f"[OCR-STRUCT] {model_name} transient error, trying next model: {e}", file=sys.stderr)
                continue
            print(f"[OCR-STRUCT] Error: {e}", file=sys.stderr)
            if model_name == MODELS[-1]:
                if key_env != "GOOGLE_AI_API_KEY":
                    raise OCRCorrectionUnavailable()
                print("[OCR-STRUCT] All Gemini tiers failed, trying Mistral OCR fallback", file=sys.stderr)
                return _ocr_with_mistral_structured(
                    image_bytes, mime_type, src, timeout_s=timeout_s, fail_reasons=fail_reasons
                )
            raise

    if data is None:
        raise RuntimeError("All Gemini models failed")

    try:
        raw = data["candidates"][0]["content"]["parts"][0]["text"]

        try:
            result = json.loads(raw)
        except json.JSONDecodeError:
            fixed = re.sub(r'(?<!\\)\\(?!["\\/bfnrtu\\])', r'\\\\', raw)
            try:
                result = json.loads(fixed)
            except json.JSONDecodeError as e2:
                print(f"[OCR-STRUCT] JSON parse failed even after fix: {e2}", file=sys.stderr)
                print(f"[OCR-STRUCT] Raw (first 500): {raw[:500]}", file=sys.stderr)
                return {"title": "", "sections": [{"type": "paragraph", "content": raw}]}

        if not isinstance(result, dict):
            result = {"title": "", "sections": [{"type": "paragraph", "content": str(result)}]}
        if "sections" not in result:
            result["sections"] = []

        # Validate figure sections — ensure bbox is a valid dict with x/y/w/h
        def _validate_figures(sections: list) -> None:
            for section in sections:
                if section.get("type") == "figure":
                    bbox = section.get("bbox")
                    if bbox and isinstance(bbox, dict):
                        # Faza 4.5d — cauza reală a bug-ului de bbox găsit în testul
                        # A/B (gemini-3.5-flash-lite): pe coordonata `y`, modelul
                        # revine uneori la scala NATIVĂ Gemini de "grounding" (0-1000),
                        # ignorând instrucțiunea explicită din prompt (fracție 0.0-1.0).
                        # Catalogat programatic pe cele 14 răspunsuri din testul A/B:
                        # exact valorile >1.0 apar DOAR pe `y`, niciodată pe x/w/h — nu
                        # e "tot bbox-ul e în pixeli" (asta ar strica și x/w/h). Verificat
                        # ARITMETIC (÷1000 reproduce exact valoarea de referință a lui
                        # 3.6-flash pe aceeași figură, ex. 551.0→0.551) ȘI VIZUAL (crop-ul
                        # rezultat e identic cu crop-ul de referință). ÷1000 e o constantă
                        # FIXĂ (scala Gemini), nu ÷dimensiunea imaginii (care nici nu ar
                        # da rezultatul corect — verificat, ar da 0.318 în loc de 0.551).
                        # Per câmp, nu tot bbox-ul deodată — x/w/h rămân neatinse dacă
                        # sunt deja în 0-1. Clamp-ul 0-1 de mai jos rămâne ca plasă de
                        # siguranță finală pt orice altă anomalie, nu doar scala 0-1000.
                        for k in ("x", "y", "w", "h"):
                            v = float(bbox.get(k, 0))
                            if v > 1.0:
                                v = v / 1000.0
                            bbox[k] = max(0.0, min(1.0, v))
                        if bbox.get("w", 0) < 0.01 or bbox.get("h", 0) < 0.01:
                            print(f"[OCR-STRUCT] Bbox too small, removed: {bbox}", file=sys.stderr)
                            section.pop("bbox", None)
                    elif bbox is not None:
                        print(f"[OCR-STRUCT] Invalid bbox type ({type(bbox).__name__}), removed", file=sys.stderr)
                        section.pop("bbox", None)
                    # Remove any legacy SVG field
                    section.pop("svg", None)
                elif section.get("type") == "two_column":
                    _validate_figures(section.get("left", []))
                    _validate_figures(section.get("right", []))

        _validate_figures(result.get("sections", []))

        figure_count = _count_figures(result.get("sections", []))
        svg_count = _count_figures_with_svg(result.get("sections", []))
        total = len(result.get("sections", []))
        print(f"[OCR-STRUCT] OK: {total} sections, {figure_count} figures ({svg_count} with SVG)", file=sys.stderr)
        return result

    except Exception as e:
        print(f"[OCR-STRUCT] Parse error: {e}", file=sys.stderr)
        raise


def _ocr_with_mistral_structured(image_bytes: bytes, mime_type: str, src_lang_name: str,
                                 *, timeout_s: int = 45,
                                 fail_reasons: list[str] | None = None) -> dict:
    """G2 — Mistral OCR fallback when all Gemini tiers are exhausted.

    Uses Mistral OCR API (1B tokens/month free, EU servers).
    Returns structured dict compatible with html_builder.py.
    Note: returns Markdown text sections only — no SVG figures generated.

    ``fail_reasons`` (Faza 4.5e, 2026-09-11): motivele celor 3 eșecuri Gemini care
    au dus aici — folosite să derivăm ``fallback_reason`` ("quota" DOAR dacă TOATE
    au fost 429, altfel "unavailable"), ca frontend-ul (E-OCR-004) să-i spună
    Cristinei DE CE, nu doar CE. Tier plătit nu ajunge niciodată aici (vezi
    ``OCRCorrectionUnavailable`` mai sus) — ``fallback_reason`` e mereu relevant
    doar pt tier-ul free (import Editor).
    """
    api_key = os.environ.get("MISTRAL_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("MISTRAL_API_KEY not set — Mistral OCR fallback unavailable")

    b64 = base64.b64encode(image_bytes).decode("utf-8")

    if mime_type == "application/pdf":
        doc_obj = {"type": "document_url", "document_url": f"data:application/pdf;base64,{b64}"}
    else:
        doc_obj = {"type": "image_url", "image_url": f"data:{mime_type};base64,{b64}"}

    payload = json.dumps({
        "model": "mistral-ocr-latest",
        "document": doc_obj,
        "include_image_base64": False,
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.mistral.ai/v1/ocr",
        data=payload,
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"},
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            result = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="replace")[:300]
        print(f"[OCR-STRUCT] Mistral OCR HTTP {e.code}: {error_body}", file=sys.stderr)
        raise RuntimeError(f"Mistral OCR error {e.code}: {error_body[:200]}")

    # Convert Mistral pages to structured sections compatible with html_builder
    sections = []
    pages = result.get("pages", [])
    for page in pages:
        markdown_text = page.get("markdown", "").strip()
        if markdown_text:
            sections.append({
                "type": "paragraph",
                "content": markdown_text,
            })

    reasons = fail_reasons or []
    fallback_reason = "quota" if reasons and all(r == "429" for r in reasons) else "unavailable"
    print(
        f"[OCR-STRUCT] Mistral OCR fallback: {len(pages)} pages, {len(sections)} sections, "
        f"fallback_reason={fallback_reason} (fail_reasons={reasons})",
        file=sys.stderr,
    )
    return {
        "title": "",
        "sections": sections,
        "source": "mistral-ocr",  # Flag for downstream: no SVG figures available
        "fallback_reason": fallback_reason,  # Faza 4.5e — E-OCR-004: "quota"|"unavailable"
    }


def _count_figures(sections: list) -> int:
    """Count all figure sections including inside two_column."""
    count = 0
    for s in sections:
        if s.get("type") == "figure":
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures(s.get("left", []) + s.get("right", []))
    return count


def _count_figures_with_svg(sections: list) -> int:
    """Count figure sections that have valid SVG content."""
    count = 0
    for s in sections:
        if s.get("type") == "figure" and s.get("svg"):
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures_with_svg(s.get("left", []) + s.get("right", []))
    return count
