"""Structured OCR using Gemini 2.5 Pro JSON mode.

Extracts text + inline SVG figures from math textbook images.
Returns structured JSON with text sections and SVG code for geometric figures.
SVG figures are generated by Gemini following school geometry conventions.
"""

from __future__ import annotations

import base64
import json
import os
import re
import sys
import urllib.request

try:
    from .retry import retry_with_backoff
except ImportError:
    from lib.retry import retry_with_backoff


def ocr_structured(image_bytes: bytes, mime_type: str, source_lang: str = "ro") -> dict:
    """Extract structured content from an image using Gemini JSON mode.

    Returns dict with "title" and "sections" list.
    Section types: heading, paragraph, step, observation, list, figure, two_column.
    Figure sections have "svg" field with inline SVG code (school geometry conventions).
    """
    api_key = os.environ.get("GOOGLE_AI_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("GOOGLE_AI_API_KEY not set")

    image_b64 = base64.b64encode(image_bytes).decode("utf-8")
    lang_names = {"ro": "Romanian", "sk": "Slovak", "en": "English"}
    src = lang_names.get(source_lang, source_lang)

    print(f"[OCR-STRUCT] Processing: {len(image_bytes)} bytes, {mime_type}, {source_lang}", file=sys.stderr)

    prompt = (
        f"Analyze this {src} math textbook page image. Return a JSON object.\n\n"
        "STRUCTURE:\n"
        '{{"title":"page title","sections":[\n'
        '  {{"type":"heading","content":"text","level":1}},\n'
        '  {{"type":"paragraph","content":"text with $LaTeX$ formulas"}},\n'
        '  {{"type":"step","content":"$P_1$: construction step text"}},\n'
        '  {{"type":"figure","bbox":{{"x":0.1,"y":0.3,"w":0.4,"h":0.2}},"caption":"optional"}},\n'
        '  {{"type":"observation","content":"observation text"}},\n'
        '  {{"type":"list","content":"1. item one\\n2. item two"}},\n'
        '  {{"type":"two_column","left":[...sections...],"right":[...sections...]}}\n'
        ']}}\n\n'

        "TEXT RULES:\n"
        "1. ALL math as LaTeX: $\\triangle ABC$, $\\angle A$, $AB = 4 \\text{{ cm}}$\n"
        "2. Construction steps (P1, P2 etc.) -> type 'step', use Unicode subscript in content\n"
        "3. Bold terms: **bold** markers\n"
        "4. Preserve EXACT text — do not summarize or skip\n"
        "5. If a word is hyphenated across a line break, join it into one word\n"
        "6. Lists: numbered (1. 2.) or lettered (a) b))\n"
        "7. IGNORE page numbers (standalone numbers like 205, 206 at edges) — do NOT include them\n"
        "8. 'Observatie.' / 'Exemplu.' / 'Definitie.' etc. MUST be bold: **Observatie.**\n\n"

        "FIGURE RULES — CRITICAL:\n"
        "7. For EVERY geometric figure/diagram, return a 'figure' section with:\n"
        "   - 'bbox': bounding box as fractions of the FULL IMAGE dimensions (0.0 to 1.0):\n"
        "     x = left_pixel / image_width,  y = top_pixel / image_height\n"
        "     w = figure_width / image_width, h = figure_height / image_height\n"
        "   - The bbox must cover ONLY that specific figure, NOT adjacent figures\n"
        "   - For figures in two_column: left-column figures have x < 0.5, right-column figures have x > 0.35\n"
        "   - Include vertex labels and measurement text inside the bbox\n"
        "   - 'caption': short description (e.g. 'Triunghi ABC')\n"
        "   Do NOT generate SVG. Return ONLY the bounding box.\n"
        "8. Each figure gets its OWN separate bbox — never share a bbox between two figures.\n"
        "9. If there is no figure, do not return a 'figure' section.\n\n"

        "LAYOUT RULES — CRITICAL:\n"
        "10. ALWAYS use type 'two_column' when ANY of these appear side-by-side on the page:\n"
        "    - A figure next to text or next to another figure\n"
        "    - Construction step P1 left + P2 right (VERY common in geometry pages)\n"
        "    - Any two elements that visually appear in columns, not stacked vertically\n"
        "    Do NOT linearize side-by-side content into sequential sections.\n"
        "    'two_column' has 'left': [...sections] and 'right': [...sections].\n"
        "    Each side can contain steps, figures, text, observations.\n"
        "11. Preserve the EXACT visual layout of the original page — vertical order AND column layout.\n\n"

        "Return ONLY valid JSON, no explanation or markdown wrapper."
    )

    contents = [{"parts": [
        {"text": prompt},
        {"inline_data": {"mime_type": mime_type, "data": image_b64}},
    ]}]

    payload = json.dumps({
        "contents": contents,
        "generationConfig": {
            "responseMimeType": "application/json",
        },
    }).encode("utf-8")

    # Fallback chain: Flash (1000 RPD) → Flash-Lite (1500 RPD) → Pro (100 RPD, quality)
    # Flash-Lite added 2026-04-06 (G1): 30 RPM / 1500 RPD — total Gemini capacity: 2600 RPD
    MODELS = ["gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.5-pro"]
    data = None

    for model_name in MODELS:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
        req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
        try:
            def _call(r=req):
                with urllib.request.urlopen(r, timeout=180) as resp:
                    return json.loads(resp.read().decode("utf-8"))

            data = retry_with_backoff(_call, max_retries=2, base_delay=1.0)
            print(f"[OCR-STRUCT] Success with {model_name}", file=sys.stderr)
            break
        except urllib.error.HTTPError as e:
            if e.code == 429 and model_name != MODELS[-1]:
                print(f"[OCR-STRUCT] {model_name} rate limited (429), trying next model", file=sys.stderr)
                continue
            error_body = e.read().decode("utf-8", errors="replace")[:300]
            print(f"[OCR-STRUCT] HTTP {e.code}: {error_body}", file=sys.stderr)
            if model_name == MODELS[-1]:
                # All Gemini tiers exhausted — try Mistral OCR as last resort
                print("[OCR-STRUCT] All Gemini tiers exhausted, trying Mistral OCR fallback", file=sys.stderr)
                return _ocr_with_mistral_structured(image_bytes, mime_type, src)
            raise
        except Exception as e:
            if "429" in str(e) and model_name != MODELS[-1]:
                print(f"[OCR-STRUCT] {model_name} quota exceeded, trying next model", file=sys.stderr)
                continue
            print(f"[OCR-STRUCT] Error: {e}", file=sys.stderr)
            if model_name == MODELS[-1]:
                print("[OCR-STRUCT] All Gemini tiers failed, trying Mistral OCR fallback", file=sys.stderr)
                return _ocr_with_mistral_structured(image_bytes, mime_type, src)
            raise

    if data is None:
        raise RuntimeError("All Gemini models failed")

    try:
        raw = data["candidates"][0]["content"]["parts"][0]["text"]

        try:
            result = json.loads(raw)
        except json.JSONDecodeError:
            fixed = re.sub(r'(?<!\\)\\(?!["\\/bfnrtu\\])', r'\\\\', raw)
            try:
                result = json.loads(fixed)
            except json.JSONDecodeError as e2:
                print(f"[OCR-STRUCT] JSON parse failed even after fix: {e2}", file=sys.stderr)
                print(f"[OCR-STRUCT] Raw (first 500): {raw[:500]}", file=sys.stderr)
                return {"title": "", "sections": [{"type": "paragraph", "content": raw}]}

        if not isinstance(result, dict):
            result = {"title": "", "sections": [{"type": "paragraph", "content": str(result)}]}
        if "sections" not in result:
            result["sections"] = []

        # Validate figure sections — ensure bbox is a valid dict with x/y/w/h
        def _validate_figures(sections: list) -> None:
            for section in sections:
                if section.get("type") == "figure":
                    bbox = section.get("bbox")
                    if bbox and isinstance(bbox, dict):
                        # Clamp all values to 0.0–1.0
                        for k in ("x", "y", "w", "h"):
                            v = float(bbox.get(k, 0))
                            bbox[k] = max(0.0, min(1.0, v))
                        if bbox.get("w", 0) < 0.01 or bbox.get("h", 0) < 0.01:
                            print(f"[OCR-STRUCT] Bbox too small, removed: {bbox}", file=sys.stderr)
                            section.pop("bbox", None)
                    elif bbox is not None:
                        print(f"[OCR-STRUCT] Invalid bbox type ({type(bbox).__name__}), removed", file=sys.stderr)
                        section.pop("bbox", None)
                    # Remove any legacy SVG field
                    section.pop("svg", None)
                elif section.get("type") == "two_column":
                    _validate_figures(section.get("left", []))
                    _validate_figures(section.get("right", []))

        _validate_figures(result.get("sections", []))

        figure_count = _count_figures(result.get("sections", []))
        svg_count = _count_figures_with_svg(result.get("sections", []))
        total = len(result.get("sections", []))
        print(f"[OCR-STRUCT] OK: {total} sections, {figure_count} figures ({svg_count} with SVG)", file=sys.stderr)
        return result

    except Exception as e:
        print(f"[OCR-STRUCT] Parse error: {e}", file=sys.stderr)
        raise


def _ocr_with_mistral_structured(image_bytes: bytes, mime_type: str, src_lang_name: str) -> dict:
    """G2 — Mistral OCR fallback when all Gemini tiers are exhausted.

    Uses Mistral OCR API (1B tokens/month free, EU servers).
    Returns structured dict compatible with html_builder.py.
    Note: returns Markdown text sections only — no SVG figures generated.
    """
    api_key = os.environ.get("MISTRAL_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("MISTRAL_API_KEY not set — Mistral OCR fallback unavailable")

    b64 = base64.b64encode(image_bytes).decode("utf-8")

    if mime_type == "application/pdf":
        doc_obj = {"type": "document_url", "document_url": f"data:application/pdf;base64,{b64}"}
    else:
        doc_obj = {"type": "image_url", "image_url": f"data:{mime_type};base64,{b64}"}

    payload = json.dumps({
        "model": "mistral-ocr-latest",
        "document": doc_obj,
        "include_image_base64": False,
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.mistral.ai/v1/ocr",
        data=payload,
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"},
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="replace")[:300]
        print(f"[OCR-STRUCT] Mistral OCR HTTP {e.code}: {error_body}", file=sys.stderr)
        raise RuntimeError(f"Mistral OCR error {e.code}: {error_body[:200]}")

    # Convert Mistral pages to structured sections compatible with html_builder
    sections = []
    pages = result.get("pages", [])
    for page in pages:
        markdown_text = page.get("markdown", "").strip()
        if markdown_text:
            sections.append({
                "type": "paragraph",
                "content": markdown_text,
            })

    print(f"[OCR-STRUCT] Mistral OCR fallback: {len(pages)} pages, {len(sections)} sections", file=sys.stderr)
    return {
        "title": "",
        "sections": sections,
        "source": "mistral-ocr",  # Flag for downstream: no SVG figures available
    }


def _count_figures(sections: list) -> int:
    """Count all figure sections including inside two_column."""
    count = 0
    for s in sections:
        if s.get("type") == "figure":
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures(s.get("left", []) + s.get("right", []))
    return count


def _count_figures_with_svg(sections: list) -> int:
    """Count figure sections that have valid SVG content."""
    count = 0
    for s in sections:
        if s.get("type") == "figure" and s.get("svg"):
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures_with_svg(s.get("left", []) + s.get("right", []))
    return count
