"""Structured OCR using Gemini 2.5 Pro JSON mode.

Extracts text + inline SVG figures from math textbook images.
Returns structured JSON with text sections and SVG code for geometric figures.
SVG figures are generated by Gemini following school geometry conventions.
"""

from __future__ import annotations

import base64
import json
import os
import re
import sys
import urllib.request

try:
    from .retry import retry_with_backoff
except ImportError:
    from lib.retry import retry_with_backoff


def ocr_structured(image_bytes: bytes, mime_type: str, source_lang: str = "ro") -> dict:
    """Extract structured content from an image using Gemini JSON mode.

    Returns dict with "title" and "sections" list.
    Section types: heading, paragraph, step, observation, list, figure, two_column.
    Figure sections have "svg" field with inline SVG code (school geometry conventions).
    """
    api_key = os.environ.get("GOOGLE_AI_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("GOOGLE_AI_API_KEY not set")

    image_b64 = base64.b64encode(image_bytes).decode("utf-8")
    lang_names = {"ro": "Romanian", "sk": "Slovak", "en": "English"}
    src = lang_names.get(source_lang, source_lang)

    print(f"[OCR-STRUCT] Processing: {len(image_bytes)} bytes, {mime_type}, {source_lang}", file=sys.stderr)

    prompt = (
        f"Analyze this {src} math textbook page image. Return a JSON object.\n\n"
        "STRUCTURE:\n"
        '{{"title":"page title","sections":[\n'
        '  {{"type":"heading","content":"text","level":1}},\n'
        '  {{"type":"paragraph","content":"text with $LaTeX$ formulas"}},\n'
        '  {{"type":"step","content":"$P_1$: construction step text"}},\n'
        '  {{"type":"figure","svg":"<svg viewBox=\\"0 0 W H\\" ...>...</svg>","caption":"optional"}},\n'
        '  {{"type":"observation","content":"observation text"}},\n'
        '  {{"type":"list","content":"1. item one\\n2. item two"}},\n'
        '  {{"type":"two_column","left":[...sections...],"right":[...sections...]}}\n'
        ']}}\n\n'

        "TEXT RULES:\n"
        "1. ALL math as LaTeX: $\\triangle ABC$, $\\angle A$, $AB = 4 \\text{{ cm}}$\n"
        "2. Construction steps (P1, P2 etc.) -> type 'step', use Unicode subscript in content\n"
        "3. Bold terms: **bold** markers\n"
        "4. Preserve EXACT text — do not summarize or skip\n"
        "5. If a word is hyphenated across a line break, join it into one word\n"
        "6. Lists: numbered (1. 2.) or lettered (a) b))\n\n"

        "FIGURE RULES — CRITICAL:\n"
        "7. For EVERY geometric figure/diagram, generate INLINE SVG code in the 'svg' field\n"
        "8. Do NOT return bbox coordinates. Generate actual <svg> elements.\n"
        "9. SVG conventions (MANDATORY):\n"
        "   a) Construction/auxiliary lines: stroke-dasharray='5,3' (dashed)\n"
        "   b) Result/final lines: solid, stroke-width='1.8'\n"
        "   c) Every vertex: <circle cx='X' cy='Y' r='2.5' fill='#333'/> + italic label\n"
        "   d) Measurements ALWAYS with unit: '4 cm' not '4'\n"
        "   e) Step labels: Unicode subscript P₁ P₂ P₃ P₄\n"
        "   f) Labels: text-anchor='middle', font-family='Cambria, serif'\n"
        "   g) Different angles: different colors (red #c44, green #1a7, blue #47c)\n"
        "   h) Right angles: small square marker (polyline), NOT arc\n"
        "   i) Final triangle/polygon: fill='#e8f0fe' + solid outline stroke-width='1.8'\n"
        "   j) Compass arcs: dashed (stroke-dasharray='4,3')\n"
        "   k) Angle arcs: thin (stroke-width='1.1'), radius ~25px\n"
        "   l) viewBox adapted per figure (NOT fixed size)\n"
        "   m) Calculate coordinates using TRIGONOMETRY for accurate geometry\n"
        "      (e.g. a 3-4-5 triangle is RIGHT-angled, draw it with a right angle)\n\n"

        "LAYOUT RULES:\n"
        "10. If the page has side-by-side content (e.g. P1 figure left, P2 figure right):\n"
        "    - Use type 'two_column' with 'left' and 'right' arrays of sections\n"
        "    - Each side can contain text, steps, and figures\n"
        "11. Preserve the exact visual layout of the original page\n\n"

        "Return ONLY valid JSON, no explanation or markdown wrapper."
    )

    contents = [{"parts": [
        {"text": prompt},
        {"inline_data": {"mime_type": mime_type, "data": image_b64}},
    ]}]

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key={api_key}"

    payload = json.dumps({
        "contents": contents,
        "generationConfig": {
            "responseMimeType": "application/json",
        },
    }).encode("utf-8")

    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})

    try:
        def _call():
            with urllib.request.urlopen(req, timeout=180) as resp:
                return json.loads(resp.read().decode("utf-8"))

        data = retry_with_backoff(_call, max_retries=2, base_delay=1.0)

        raw = data["candidates"][0]["content"]["parts"][0]["text"]

        try:
            result = json.loads(raw)
        except json.JSONDecodeError:
            fixed = re.sub(r'(?<!\\)\\(?!["\\/bfnrtu\\])', r'\\\\', raw)
            try:
                result = json.loads(fixed)
            except json.JSONDecodeError as e2:
                print(f"[OCR-STRUCT] JSON parse failed even after fix: {e2}", file=sys.stderr)
                print(f"[OCR-STRUCT] Raw (first 500): {raw[:500]}", file=sys.stderr)
                return {"title": "", "sections": [{"type": "paragraph", "content": raw}]}

        if not isinstance(result, dict):
            result = {"title": "", "sections": [{"type": "paragraph", "content": str(result)}]}
        if "sections" not in result:
            result["sections"] = []

        # Validate SVG figures — ensure they have actual SVG content
        for section in result.get("sections", []):
            if section.get("type") == "figure":
                svg = section.get("svg", "")
                if svg and "<svg" not in svg.lower():
                    print(f"[OCR-STRUCT] Invalid SVG removed (no <svg> tag)", file=sys.stderr)
                    section.pop("svg", None)
                # Legacy: remove any bbox fields (deprecated D24)
                section.pop("bbox", None)
            # Recurse into two_column sections
            if section.get("type") == "two_column":
                for sub in section.get("left", []) + section.get("right", []):
                    if sub.get("type") == "figure":
                        svg = sub.get("svg", "")
                        if svg and "<svg" not in svg.lower():
                            sub.pop("svg", None)
                        sub.pop("bbox", None)

        figure_count = _count_figures(result.get("sections", []))
        svg_count = _count_figures_with_svg(result.get("sections", []))
        total = len(result.get("sections", []))
        print(f"[OCR-STRUCT] OK: {total} sections, {figure_count} figures ({svg_count} with SVG)", file=sys.stderr)
        return result

    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="replace")[:300]
        print(f"[OCR-STRUCT] HTTP {e.code}: {error_body}", file=sys.stderr)
        raise
    except Exception as e:
        print(f"[OCR-STRUCT] Error: {e}", file=sys.stderr)
        raise


def _count_figures(sections: list) -> int:
    """Count all figure sections including inside two_column."""
    count = 0
    for s in sections:
        if s.get("type") == "figure":
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures(s.get("left", []) + s.get("right", []))
    return count


def _count_figures_with_svg(sections: list) -> int:
    """Count figure sections that have valid SVG content."""
    count = 0
    for s in sections:
        if s.get("type") == "figure" and s.get("svg"):
            count += 1
        elif s.get("type") == "two_column":
            count += _count_figures_with_svg(s.get("left", []) + s.get("right", []))
    return count
