import type { CurriculumCycle } from "../types";

// Gimnaziu (clasele V-VIII) — programe aprobate OMEN 3393/2017 (matematică și
// științe), 3393/2017 (limbă etc.). Extras din Carla/Curricula/config_gimnaziu.json.
// NOTĂ: config-ul e sursa autoritativă pt LISTA de materii (skeleton).
// F1 (2026-08-08): regulamente proprii Matematică Cl.6/7/8 (Cl.5 din F0).
// "Faza toate materiile" (2026-08-08): regulamente proprii pt TOATE materiile
// rămase (Limba Română, Limba Engleză, Istorie, Geografie, Biologie, Fizică,
// Chimie, Educație Tehnologică, Informatică-TIC, Educație Socială), sursate
// direct din PDF-urile oficiale OMEN 3393/2017 (rocnee.eu) de 10 subagenți
// paraleli organizați pe materie (across clase, ca la F4 Grădiniță — prinde
// inconsistențe de progresie V→VI→VII→VIII). Mai multe corecții reale față de
// presupuneri inițiale (progresia adevărată diferă de ce era de așteptat la
// Istorie/Geografie/Biologie/Educație Socială/Informatică — vezi capitolele,
// derivate exclusiv din sursa verificată, nu din presupuneri).

const gimnaziu: CurriculumCycle = {
  id: "gimnaziu",
  nume: "Gimnaziu",
  sursa_url:
    "https://rocnee.eu/index.php/dcee-oriz/curriculum-oriz/programe-scolare-front/planuri-cadru-de-invatamant-si-programe-scolare-invatamant-gimnazial-2023",
  data_extragere: "2026-08-08",
  nivele: [
    {
      id: "clasa-5",
      nume: "Clasa a V-a",
      sursa_cheie: "Clasa_5",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          regulament_ref: "gimnaziu/clasa-5/limba-romana",
          capitole: [
            "Lectură și înțelegerea textului (temă, idee principală, personaj, plan simplu de idei)",
            "Sintaxă — propoziția (enunț, predicat verbal, subiect, acordul predicat-subiect, atribut)",
            "Morfologie — părțile de vorbire (verb, substantiv, prepoziție, pronume, adjectiv, numeral)",
            "Ortografie și ortoepie (alfabet, sunete, silabă, accent)",
            "Vocabular (sinonime, antonime, câmp lexical)",
            "Variație stilistică (limba standard, normă și abatere, istoria cuvintelor)",
            "Elemente de interculturalitate (identitate personală/națională, carte românească, legende greco-romane)",
            "Redactare (text scurt cu plan simplu, descriere)",
          ],
        },
        {
          // PILOT F0 — îmbogățit cu capitolele din programa oficială OMEN 3393/2017.
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          regulament_ref: "gimnaziu/clasa-5/matematica",
          capitole: [
            "Numere naturale (operații, puteri cu exponent natural, ordinea operațiilor)",
            "Divizibilitate (divizori, multipli, criterii)",
            "Metode aritmetice de rezolvare a problemelor",
            "Mulțimi (notații, operații cu mulțimi)",
            "Fracții ordinare (operații, compararea)",
            "Fracții zecimale (operații, aproximări)",
            "Unități de măsură (lungime, arie, volum, masă, timp)",
            "Elemente de geometrie (unghiuri, triunghi, patrulater, perimetru, arie)",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          regulament_ref: "gimnaziu/clasa-5/limba-engleza",
          capitole: [
            "Present Simple",
            "Present Continuous",
            "Imperative + can/may",
            "Nouns/articles/demonstratives",
            "Adjectives, possessives, ordinal numbers",
            "Vocabular tematic A1 (familie, animale, hrană, cumpărături, sărbători)",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          regulament_ref: "gimnaziu/clasa-5/istorie",
          capitole: [
            "Alfabetul istoriei",
            "Preistoria",
            "Orientul Antic",
            "Civilizația greacă și sinteza elenistică",
            "Lumea romană",
            "Geto-dacii",
            "Civilizația islamică",
            "Europa medievală",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          regulament_ref: "gimnaziu/clasa-5/geografie",
          capitole: [
            "Terra – o planetă a Universului",
            "Terra – o planetă în mișcare (coordonate, orientare, timp)",
            "Geosferele Terrei (litosferă/atmosferă/hidrosferă/biosferă)",
            "Zonele naturale ale Terrei",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          regulament_ref: "gimnaziu/clasa-5/biologie",
          capitole: [
            "Viețuitoarele în mediul lor de viață (ecosistem, biotop, biocenoză)",
            "Relații între viețuitoare (hrănire, reproducere, apărare)",
            "Omul și mediul (impact, prevenire infestări)",
            "Alte medii de viață din țară și din lume",
            "Grupe de viețuitoare (bacterii, protiste, ciuperci, plante, animale)",
          ],
        },
        {
          id: "educatie-tehnologica",
          nume: "Educație Tehnologică",
          sursa_nume: "Educatie Tehnologica",
          regulament_ref: "gimnaziu/clasa-5/educatie-tehnologica",
          capitole: [
            "Tehnologii de cultivare a plantelor și creșterea animalelor",
            "Tehnologii de preparare a hranei (gastronomie)",
            "Desen geometric aplicat (peisagistică, decorare mese)",
            "Calitatea produselor alimentare și protecția consumatorului",
            "Alimentație echilibrată și produse ecologice",
          ],
        },
        {
          id: "informatica-tic",
          nume: "Informatică și TIC",
          sursa_nume: "Informatica si TIC",
          regulament_ref: "gimnaziu/clasa-5/informatica-tic",
          capitole: [
            "Norme de siguranță și arhitectura calculatorului",
            "Dispozitive de intrare/ieșire/stocare",
            "Sisteme de operare",
            "Internet",
            "Editoare grafice",
            "Algoritmi introductivi (secvențial, alternativ)",
          ],
        },
        {
          id: "educatie-sociala",
          nume: "Educație Socială",
          sursa_nume: "Educatie Sociala",
          regulament_ref: "gimnaziu/clasa-5/educatie-sociala",
          capitole: [
            "Formularea de întrebări (valoarea întrebărilor, cum se adresează)",
            "Argumentarea unui punct de vedere personal (fapte vs. opinii, stereotipuri, persuasiune)",
            "Drepturi și responsabilități ale copilului (Convenția ONU, drepturi concrete)",
            "Respectarea, apărarea și promovarea drepturilor copilului (instituții, categorii de risc)",
            "Proiectul educațional (promovarea drepturilor copilului)",
          ],
        },
      ],
    },
    {
      id: "clasa-6",
      nume: "Clasa a VI-a",
      sursa_cheie: "Clasa_6",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          regulament_ref: "gimnaziu/clasa-6/limba-romana",
          capitole: [
            "Lectură — textul narativ (narator, persoana I/III, momentele subiectului), textul argumentativ (noțiune inițială)",
            "Sintaxă — propoziția (predicat nominal, subiect neexprimat, complement direct/indirect, circumstanțial de mod/timp)",
            "Morfologie — verbul la conjunctiv/condițional-optativ, substantivul (caz, articol genitival), pronumele reflexiv, adverbul",
            "Ortografie și ortoepie (diftong, triftong, hiat, despărțirea în silabe)",
            "Vocabular (omonime, cuvinte polisemantice, sens propriu/figurat)",
            "Variație stilistică (limbă vorbită, limbă scrisă)",
            "Elemente de interculturalitate (legendele popoarelor, limba română în Europa, cultura populară)",
            "Redactare (rezumat, transformarea vorbirii directe în indirectă)",
          ],
        },
        {
          // F1 — regulament propriu (era copie Clasa 5, bug „7 regulamente").
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          regulament_ref: "gimnaziu/clasa-6/matematica",
          capitole: [
            "Mulțimi și divizibilitate (operații cu mulțimi, descompunere în factori primi, c.m.m.d.c./c.m.m.m.c.)",
            "Rapoarte și proporții (regula de trei simplă, mărimi direct/invers proporționale)",
            "Mulțimea numerelor întregi (operații, ecuații/inecuații)",
            "Mulțimea numerelor raționale (operații, ecuații liniare simple)",
            "Noțiuni geometrice fundamentale (unghiuri, drepte paralele/perpendiculare, cercul)",
            "Triunghiul (construcție, congruență, linii importante, teorema lui Pitagora)",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          regulament_ref: "gimnaziu/clasa-6/limba-engleza",
          capitole: [
            "Present Simple vs Continuous",
            "Past Simple (regulat/neregulat) + used to",
            "Future Simple",
            "Tag questions + genitiv",
            "Comparație neregulată + conectori + adverbe",
            "Vocabular extins (personalități, sport, tradiții, transport)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          regulament_ref: "gimnaziu/clasa-6/fizica",
          capitole: [
            "Introducere în studiul fizicii (mărimi, unități, măsurare)",
            "Fenomene mecanice (mișcare, viteză, masă, densitate, forță, greutate)",
            "Fenomene termice (temperatură, dilatare, schimbări de stare)",
            "Fenomene electrice și magnetice (magneți, circuit electric simplu, serie/paralel)",
            "Fenomene optice (lumină, umbră, reflexie/refracție calitativ)",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          regulament_ref: "gimnaziu/clasa-6/istorie",
          capitole: [
            "Călători și călătorii — Europa și Lumea Nouă",
            "Geneza spiritului modern",
            "Spre o nouă societate",
            "Secolul naționalităților",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          regulament_ref: "gimnaziu/clasa-6/geografie",
          capitole: [
            "Cunoașterea lumii în care trăim",
            "Antroposfera – omul și activitățile umane",
            "Europa – identitate geografică",
            "Europa în lumea contemporană (UE)",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          regulament_ref: "gimnaziu/clasa-6/biologie",
          capitole: [
            "Organismul — un tot unitar (organe, țesuturi, celule)",
            "Hrănirea (fotosinteza, sistem digestiv)",
            "Respirația (sistem respirator)",
            "Circulația (sistem circulator, sânge, grupe sanguine)",
            "Excreția (sistem excretor)",
            "Relații între funcțiile de nutriție, igienă",
          ],
        },
        {
          id: "educatie-tehnologica",
          nume: "Educație Tehnologică",
          sursa_nume: "Educatie Tehnologica",
          regulament_ref: "gimnaziu/clasa-6/educatie-tehnologica",
          capitole: [
            "Construcții la scară (machete)",
            "Limbaj grafic aplicat (planuri, scară)",
            "Mediul construit (clădiri, rețele de utilități)",
            "Buget financiar și de timp",
            "Dezvoltare durabilă în construcții/transport",
          ],
        },
        {
          id: "informatica-tic",
          nume: "Informatică și TIC",
          sursa_nume: "Informatica si TIC",
          regulament_ref: "gimnaziu/clasa-6/informatica-tic",
          capitole: [
            "Prezentări",
            "Animații grafice și modele 3D",
            "Algoritmi cu structuri repetitive",
            "Internet și siguranță",
          ],
        },
        {
          id: "educatie-sociala",
          nume: "Educație Socială",
          sursa_nume: "Educatie Sociala",
          regulament_ref: "gimnaziu/clasa-6/educatie-sociala",
          capitole: [
            "Diversitatea culturală în societatea contemporană",
            "Identitate culturală proprie și a celorlalți (patrimoniu, tradiții, patriotism)",
            "Principii și valori ale societății interculturale (și abateri: intoleranță, discriminare)",
            "Comunicarea interculturală (bariere, stereotipuri, reguli de facilitare)",
            "Proiectul educațional intercultural",
          ],
        },
      ],
    },
    {
      id: "clasa-7",
      nume: "Clasa a VII-a",
      sursa_cheie: "Clasa_7",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          regulament_ref: "gimnaziu/clasa-7/limba-romana",
          capitole: [
            "Lectură — textul epic, dramatic și liric (caracterizarea personajului, dialog, indicații scenice)",
            "Sintaxă — fraza (coordonare, subordonare, atributul, circumstanțialul de cauză/scop)",
            "Morfologie — forme verbale nepersonale, pronume/adjective pronominale (posesiv, demonstrativ, relativ, nehotărât), numeral, interjecție",
            "Ortografie și ortoepie (accentul și variantele accentuale)",
            "Vocabular (derivare, compunere, familie lexicală, paronime, pleonasm)",
            "Variație stilistică (limbaj popular, termeni științifici, variație regională, diminutive)",
            "Elemente de interculturalitate (mitologie românească, țările vecine, contacte culturale)",
            "Redactare (caracterizare de personaj, jurnal de călătorie, interviu)",
          ],
        },
        {
          // F1 — regulament propriu (era copie Clasa 5, bug „7 regulamente").
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          regulament_ref: "gimnaziu/clasa-7/matematica",
          capitole: [
            "Mulțimea numerelor reale (radicali, numere iraționale, ℕ⊂ℤ⊂ℚ⊂ℝ)",
            "Ecuații și sisteme de ecuații liniare",
            "Elemente de organizare a datelor (sistem de axe ortogonale)",
            "Patrulaterul (paralelogram, dreptunghi, romb, pătrat, trapez)",
            "Cercul (unghi înscris, coarde, arce, tangente, poligoane regulate)",
            "Asemănarea triunghiurilor (teorema lui Thales)",
            "Relații metrice în triunghiul dreptunghic (Pitagora, trigonometrie)",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          regulament_ref: "gimnaziu/clasa-7/limba-engleza",
          capitole: [
            "Past Continuous",
            "Present Perfect Simple/Continuous vs Past Simple",
            "Forme de viitor (going to/will/continuous)",
            "Verbe modale (could/might/must/may not)",
            "Condițional tip 1 + propoziții temporale",
            "Vocabular extins (știri, cariere, tehnologie, mituri)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          regulament_ref: "gimnaziu/clasa-7/fizica",
          capitole: [
            "Mărimi scalare/vectoriale",
            "Interacțiuni și forțe (principiul inerției, acțiune-reacțiune, compunere forțe)",
            "Lucru mecanic și energie",
            "Echilibrul corpurilor (moment, pârghie, scripete)",
            "Statica fluidelor (presiune, Pascal, Arhimede)",
            "Unde mecanice — sunetul",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          regulament_ref: "gimnaziu/clasa-7/chimie",
          capitole: [
            "Chimia și viața. Substanțele în natură",
            "Aerul. Apa. Solul",
            "Atom. Element chimic",
            "Tabelul Periodic. Ioni. Molecule",
            "Substanțe chimice (simple/compuse, acizi/baze, pH)",
            "Calcule pe baza formulei chimice (mol, masă molară)",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          regulament_ref: "gimnaziu/clasa-7/istorie",
          capitole: [
            "Lumea la sfârșitul sec. XIX/începutul sec. XX",
            "Perioada interbelică",
            "Lumea în război",
            "Lumea postbelică",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          regulament_ref: "gimnaziu/clasa-7/geografie",
          capitole: [
            "Asia",
            "Africa",
            "America de Nord și de Sud",
            "Australia/Oceania/Antarctica",
            "Elemente de geografia mediului înconjurător",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          regulament_ref: "gimnaziu/clasa-7/biologie",
          capitole: [
            "Sensibilitate și mișcare la plante",
            "Sistemul nervos la om",
            "Organele de simț la om",
            "Glandele endocrine la om",
            "Sistemul locomotor la om (schelet, mușchi)",
            "Funcția de reproducere (plante, vertebrate, om)",
          ],
        },
        {
          id: "educatie-tehnologica",
          nume: "Educație Tehnologică",
          sursa_nume: "Educatie Tehnologica",
          regulament_ref: "gimnaziu/clasa-7/educatie-tehnologica",
          capitole: [
            "Tehnologii de execuție (textile/lemn/metal)",
            "Fișa tehnologică (material, scule, etape)",
            "Limbaj grafic aplicat (desen tehnic/schiță)",
            "Proprietățile materialelor",
            "Analiza produsului",
            "Securitate în muncă",
          ],
        },
        {
          id: "informatica-tic",
          nume: "Informatică și TIC",
          sursa_nume: "Informatica si TIC",
          regulament_ref: "gimnaziu/clasa-7/informatica-tic",
          capitole: [
            "Editor de texte / tehnoredactare",
            "Prelucrare audio-video",
            "Aplicații colaborative",
            "Limbaj de programare real (Python/C/C++/Ruby)",
          ],
        },
        {
          id: "educatie-sociala",
          nume: "Educație Socială",
          sursa_nume: "Educatie Sociala",
          regulament_ref: "gimnaziu/clasa-7/educatie-sociala",
          capitole: [
            "Drepturile omului. Forme de guvernământ și regimuri politice",
            "Constituția României (structură, valori și principii constituționale)",
            "Principii și instituții democratice (separarea puterilor, statul de drept)",
            "Domnia legii și puterea cetățenilor (drepturi, libertăți, justiție)",
            "Cetățenia activă (alegeri, societate civilă, rolul mass-media)",
            "Proiectul educațional dedicat problemelor comunității",
          ],
        },
      ],
    },
    {
      id: "clasa-8",
      nume: "Clasa a VIII-a",
      sursa_cheie: "Clasa_8",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          regulament_ref: "gimnaziu/clasa-8/limba-romana",
          capitole: [
            "Lectură — texte cu structuri combinate (narativ, descriptiv, argumentativ), figuri de stil (aliterație, hiperbolă, antiteză)",
            "Sintaxă — fraza extinsă (construcții pasive/impersonale/concesive, apoziția, propoziții subordonate după funcția sintactică)",
            "Ortografie și ortoepie (cuvinte de origine străină)",
            "Vocabular (conversiune, împrumuturi lexicale)",
            "Variație stilistică (jargon, argou, registru colocvial/cultivat)",
            "Elemente de interculturalitate (literatura universală, relații culturale, valori românești în lume)",
            "Redactare (text de opinie, text argumentativ, cronică de film/spectacol)",
          ],
        },
        {
          // F1 — regulament propriu (era copie Clasa 5, bug „7 regulamente").
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          regulament_ref: "gimnaziu/clasa-8/matematica",
          capitole: [
            "Intervale de numere reale. Inecuații în ℝ",
            "Calcul algebric în ℝ (formule de calcul prescurtat, descompuneri în factori, ecuații de gradul II)",
            "Funcții (f(x)=ax+b, elemente de statistică)",
            "Elemente ale geometriei în spațiu (corpuri geometrice, paralelism, perpendicularitate)",
            "Arii și volume ale corpurilor geometrice (prismă, piramidă, cilindru, con, sferă)",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          regulament_ref: "gimnaziu/clasa-8/limba-engleza",
          capitole: [
            "Past Perfect Simple/Continuous",
            "Future in the Past + concordanța timpurilor",
            "Vorbire indirectă (Reported Speech)",
            "Diateza pasivă (Passive Voice)",
            "Verbe modale (may/should/need/needn't)",
            "Condițional 2/3 + pronume relative",
            "Vocabular extins (civilizații, comunitate, probleme globale)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          regulament_ref: "gimnaziu/clasa-8/fizica",
          capitole: [
            "Fenomene termice (calorimetrie)",
            "Electrostatica",
            "Electrocinetica (legea lui Ohm, grupare rezistoare, legea lui Joule)",
            "Efect magnetic al curentului",
            "Fenomene optice (reflexie, refracție, lentile)",
            "Energia și viața",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          regulament_ref: "gimnaziu/clasa-8/chimie",
          capitole: [
            "Reacții chimice. Ecuații chimice",
            "Tipuri de reacții chimice (combinare/descompunere/substituție/schimb)",
            "Calcule stoechiometrice",
            "Importanța chimiei în viața noastră (combustibili, materiale de construcții, îngrășăminte, reciclare)",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          regulament_ref: "gimnaziu/clasa-8/istorie",
          capitole: [
            "Introducere",
            "Preistoria în spațiul românesc",
            "Geto-dacii",
            "Etnogeneza românească",
            "Evul Mediu românesc",
            "Modernitatea timpurie",
            "Lumea românească până la jumătatea sec. XIX",
            "România modernă",
            "România secolelor XX-XXI",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          regulament_ref: "gimnaziu/clasa-8/geografie",
          capitole: [
            "Poziția geografică a României",
            "Relieful României",
            "Clima, apele, vegetația, fauna și solurile",
            "Populația, așezările și organizarea administrativ-teritorială",
            "Activitățile economice",
            "Regiuni geografice, mediul înconjurător și România în Europa/lume",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          regulament_ref: "gimnaziu/clasa-8/biologie",
          capitole: [
            "Ereditatea și variabilitatea (material genetic, cromozomi, ADN)",
            "Transmiterea materialului genetic (caractere dominante/recesive)",
            "Evoluționism (teorii, dovezi, factori ai evoluției)",
            "Sănătatea omului și a mediului (calitate aer/apă/sol, boli)",
            "Resurse energetice, biodiversitate, dezvoltare durabilă",
          ],
        },
        {
          id: "educatie-sociala",
          nume: "Educație Socială",
          sursa_nume: "Educatie Sociala",
          regulament_ref: "gimnaziu/clasa-8/educatie-sociala",
          capitole: [
            "Cetățenia, dimensiunea economică (consumator, producător)",
            "Banii și bugetul (planuri de acțiune, venituri-cheltuieli, mijloace de plată)",
            "Relația consumatorului cu instituțiile bancare și financiare nebancare",
            "Proiectul educațional pe teme economico-financiare",
          ],
        },
      ],
    },
  ],
};

export default gimnaziu;
