import type { CurriculumCycle } from "../types";

// Liceu (clasele IX-XII) — SUB REFORMĂ CURRICULARĂ ACTIVĂ ȘI IMINENTĂ.
// „Toate materiile" (2026-08-08): 40 regulamente proprii scrise de 10 subagenți
// paraleli, organizați pe materie (across clase), sursate din programele oficiale
// CURENTE (pre-reformă): OMECT 3458/2004, OMEC 4598/2004, OMEdC/OMEN 3252/2006,
// OMEdC 5959/2006, OMECI 5099/2009 — toate încă LEGAL VALABILE la data scrierii.
// DESCOPERIRE CRITICĂ (verificată de mai mulți subagenți independent, la sursă):
// reforma pt Clasa a IX-a NU mai e „175 programe în transparență" — e deja APROBATĂ
// și PUBLICATĂ (Ordinul 6.930/19.12.2025, Monitorul Oficial Partea I nr. 4 bis din
// 08.01.2026) și intră în vigoare chiar din anul școlar 2026-2027 (la câteva
// săptămâni de la data acestei sesiuni). Clasele X-XI-XII rămân pe programa veche
// încă 1-3 ani (reformă eșalonată). Regulamentele Clasei IX au risc de staleness
// CEL MAI MARE dintre toate — fiecare fișier `liceu_clasa9_*.md` conține un
// avertisment explicit de re-verificare. Nu presupune stabilitate — vezi §4/§8 din
// docs/PLAN_SCOLARE_2026-08-07.md.

const liceu: CurriculumCycle = {
  id: "liceu",
  nume: "Liceu",
  sursa_url:
    "https://rocnee.eu/index.php/dcee-oriz/curriculum-oriz/programe-scolare-front",
  data_extragere: "2026-08-08",
  in_reforma: true,
  nivele: [
    {
      id: "clasa-9",
      nume: "Clasa a IX-a",
      sursa_cheie: "Clasa_9",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/limba-romana",
          capitole: [
            "Grupaje tematice (Adolescența/Joc și joacă, Familia/Școala, Iubirea, Aventură-călătorie/Lumi fantastice)",
            "Ficțiune și realitate (texte nonliterare)",
            "Literatură și alte arte (film)",
            "Limbă și comunicare (dialog/monolog, niveluri ale mesajului)",
          ],
        },
        {
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/matematica",
          capitole: [
            "Mulțimi și logică matematică",
            "Șiruri",
            "Funcții și lecturi grafice",
            "Funcția de gradul I/II aprofundată",
            "Vectori în plan",
            "Calcul vectorial în geometrie",
            "Trigonometrie în geometrie",
          ],
        },
        {
          id: "informatica",
          nume: "Informatică",
          sursa_nume: "Informatica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/informatica",
          capitole: [
            "Informatica și societatea; algoritmi și date",
            "Reprezentarea algoritmilor în pseudocod",
            "Algoritmi elementari — prelucrarea numerelor",
            "Algoritmi elementari — prelucrarea secvențelor de valori",
            "Structuri de control — citirea unui program scurt",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/limba-engleza",
          capitole: [
            "Teme (personal/public/ocupațional/educațional)",
            "Gramatică funcțională (acte de vorbire)",
            "Gramatică (tag questions, Conditional 3, sistematizare timpuri)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/fizica",
          capitole: [
            "Optică geometrică (lentile, formula lentilelor, ochi, instrumente optice)",
            "Principii și legi în mecanica newtoniană",
            "Teoreme de variație și legi de conservare în mecanică",
            "Elemente de statică",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/chimie",
          capitole: [
            "Structura atomului și legături chimice",
            "Soluții (dizolvare, concentrații, pH calitativ)",
            "Reacții redox și pilă galvanică",
            "Gazul ideal",
            "Echilibru chimic (extindere profil real)",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/biologie",
          capitole: [
            "Diversitatea lumii vii (taxonomie, 5 regnuri + virusuri)",
            "Celula (structură/ultrastructură, mitoză/meioză)",
            "Ereditate mendeliană",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/istorie",
          capitole: [
            "Antichitate → popoare medievale",
            "Umanism/Renaștere",
            "Reforma religioasă",
            "Absolutism",
            "Războiul de 30 de ani (Pacea Westfalică)",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/geografie",
          capitole: [
            "Pământul – entitate a Universului",
            "Măsurarea și reprezentarea spațiului terestru",
            "Relieful terestru",
            "Atmosfera terestră",
            "Apele Terrei",
            "Viața și solurile pe Terra",
          ],
        },
        {
          id: "logica",
          nume: "Logică și Argumentare",
          sursa_nume: "Logica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-9/logica",
          capitole: [
            "Societate și comunicare",
            "Societate, comunicare și argumentare",
            "Societate, comunicare și argumentare corectă",
          ],
        },
      ],
    },
    {
      id: "clasa-10",
      nume: "Clasa a X-a",
      sursa_cheie: "Clasa_10",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/limba-romana",
          capitole: [
            "Proză narativă (basm cult/nuvelă/roman)",
            "Text dramatic (comedia)",
            "Text poetic (prozodie, tropi, lirism obiectiv/subiectiv)",
            "Registre stilistice",
            "Eseu structurat",
          ],
        },
        {
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/matematica",
          capitole: [
            "Mulțimi de numere (puteri/radicali/logaritmi/numere complexe)",
            "Funcții și ecuații (inclusiv trigonometrice)",
            "Metode de numărare",
            "Matematici financiare/statistică",
            "Geometrie analitică",
          ],
        },
        {
          id: "informatica",
          nume: "Informatică",
          sursa_nume: "Informatica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/informatica",
          capitole: [
            "Elementele de bază ale limbajului C++",
            "Structuri de control în C++",
            "Tablouri unidimensionale și bidimensionale",
            "Fișiere text",
            "Algoritmi fundamentali — căutare, sortare, interclasare",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/limba-engleza",
          capitole: [
            "Teme",
            "Gramatică funcțională",
            "Gramatică (diateză pasivă/activă, gerunziu/infinitiv, comparație intensivă, genitiv complet)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/fizica",
          capitole: [
            "Elemente de termodinamică",
            "Producerea și utilizarea curentului continuu",
            "Producerea și utilizarea curentului alternativ",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/chimie",
          capitole: [
            "Introducere în chimia organică",
            "Hidrocarburi (alcani/alchene/alchine/arene)",
            "Alcooli și acid acetic",
            "Compuși organici cu acțiune biologică",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/biologie",
          capitole: [
            "Țesuturi vegetale și animale",
            "Nutriție comparată (fotosinteză/heterotrofie/digestie)",
            "Respirație/Circulație/Excreție comparate",
            "Funcții de relație și reproducere comparate",
            "Dezechilibre ecologice",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/istorie",
          capitole: [
            "Epoca luminilor",
            "Revoluția industrială",
            "1848",
            "Statul modern",
            "Interbelic",
            "Conflictele sec. XX",
            "Mileniul III",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/geografie",
          capitole: [
            "Geografie politică",
            "Geografia populației și a așezărilor umane",
            "Geografie economică (resurse, agricultură, industrie, servicii)",
            "Ansamblurile economice și geopolitice ale lumii",
          ],
        },
        {
          id: "psihologie",
          nume: "Psihologie",
          sursa_nume: "Psihologie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-10/psihologie",
          capitole: [
            "Procese psihice",
            "Structura personalității",
            "Dezvoltarea personalității",
            "Conduita psihosocială",
          ],
        },
      ],
    },
    {
      id: "clasa-11",
      nume: "Clasa a XI-a",
      sursa_cheie: "Clasa_11",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/limba-romana",
          capitole: [
            "Fundamentele culturii române",
            "Perioada veche",
            "Curente XVII-XVIII",
            "Secolul XIX–început XX (pașoptism, Romantism, Realism, Simbolism)",
            "Romanul interbelic",
          ],
        },
        {
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/matematica",
          capitole: [
            "Permutări, matrice și determinanți",
            "Sisteme liniare",
            "Limite de funcții",
            "Continuitate",
            "Derivabilitate",
            "Reprezentare grafică de funcții și conice",
          ],
        },
        {
          id: "informatica",
          nume: "Informatică",
          sursa_nume: "Informatica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/informatica",
          capitole: [
            "Subprograme — declarare, apel, parametri",
            "Recursivitate",
            "Șiruri de caractere și structuri neomogene",
            "Liste, stive, cozi",
            "Metodele Divide et Impera și Backtracking",
            "Grafuri orientate și neorientate",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/limba-engleza",
          capitole: [
            "Teme",
            "Gramatică funcțională (subset consolidare)",
            "Gramatică (diateză pasivă directă, modal perfect, plural neregulat/colectiv)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/fizica",
          capitole: [
            "Oscilații și unde mecanice",
            "Oscilații și unde electromagnetice",
            "Optică ondulatorie",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/chimie",
          capitole: [
            "Clase de compuși organici (grupe funcționale)",
            "Reacții ale compușilor organici",
            "Compuși cu importanță biologică — biochimie structurală",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/biologie",
          capitole: [
            "Alcătuirea corpului uman",
            "Sistem nervos și analizatori",
            "Glande endocrine",
            "Mișcare (sistem osos și muscular)",
            "Nutriție (digestie/circulație/respirație/excreție/metabolism)",
            "Reproducere și homeostazie",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/istorie",
          capitole: [
            "Popoare și spații istorice (sec. XX)",
            "Oamenii, societatea și lumea ideilor",
            "Statul și politica",
            "Relațiile internaționale",
            "Religia și viața religioasă",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/geografie",
          capitole: [
            "Mediul înconjurător – problemă fundamentală a lumii contemporane",
            "Regionalizarea și globalizarea lumii contemporane",
            "Populația, resursele naturale și dezvoltarea lumii contemporane",
            "Sistemul economic și sistemul geopolitic",
          ],
        },
        {
          id: "economie",
          nume: "Economie",
          sursa_nume: "Economie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-11/economie",
          capitole: [
            "Consumatorul",
            "Producătorul/Întreprinzătorul",
            "Piața",
            "Economia deschisă",
          ],
        },
      ],
    },
    {
      id: "clasa-12",
      nume: "Clasa a XII-a",
      sursa_cheie: "Clasa_12",
      tip: "materie",
      noduri: [
        {
          id: "limba-romana",
          nume: "Limba și Literatura Română",
          sursa_nume: "Limba si Literatura Romana",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/limba-romana",
          capitole: [
            "Perioada interbelică (poezia — Bacovia, Arghezi, Blaga, Barbu)",
            "Perioada postbelică",
            "Postmodernismul",
            "Eseu argumentativ",
            "Dezbatere",
          ],
        },
        {
          id: "matematica",
          nume: "Matematică",
          sursa_nume: "Matematica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/matematica",
          capitole: [
            "Grupuri, inele și corpuri",
            "Inele de polinoame",
            "Primitive",
            "Integrala definită",
            "Aplicații ale integralei",
          ],
        },
        {
          id: "informatica",
          nume: "Informatică",
          sursa_nume: "Informatica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/informatica",
          capitole: [
            "Modelul conceptual al bazelor de date",
            "Tabele și operații specifice",
            "Chei, integritate referențială, normalizare",
            "Introducere în SQL — SELECT/INSERT/UPDATE/DELETE",
            "SQL avansat — grupare, sortare, JOIN",
          ],
        },
        {
          id: "limba-engleza",
          nume: "Limba Engleză",
          sursa_nume: "Limba Engleza",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/limba-engleza",
          capitole: [
            "Teme",
            "Gramatică funcțională (subset avansat)",
            "Gramatică (diateză pasivă indirectă, participle clauses, structuri comparative complexe)",
          ],
        },
        {
          id: "fizica",
          nume: "Fizică",
          sursa_nume: "Fizica",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/fizica",
          capitole: [
            "Teoria relativității restrânse",
            "Elemente de fizică cuantică",
            "Fizică atomică",
            "Semiconductoare. Aplicații în electronică",
            "Fizică nucleară",
          ],
        },
        {
          id: "chimie",
          nume: "Chimie",
          sursa_nume: "Chimie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/chimie",
          capitole: [
            "Clasificarea reacțiilor chimice",
            "Termochimie",
            "Cinetică chimică",
            "Echilibre acido-bazice și electrochimie",
          ],
        },
        {
          id: "biologie",
          nume: "Biologie",
          sursa_nume: "Biologie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/biologie",
          capitole: [
            "Genetică moleculară (ADN/ARN, reglaj genetic)",
            "Genetică umană (genom, mutageneză, imunogenetică)",
            "Bioetică (sfat genetic, diagnostic prenatal, terapie genică)",
            "Ecologie umană (ecosisteme antropizate, dezvoltare durabilă)",
          ],
        },
        {
          id: "istorie",
          nume: "Istorie",
          sursa_nume: "Istorie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/istorie",
          capitole: [
            "Popoare și spații istorice (sec. IX-XX, România)",
            "Statul și diplomația",
            "Cultura",
            "Religia",
          ],
        },
        {
          id: "geografie",
          nume: "Geografie",
          sursa_nume: "Geografie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/geografie",
          capitole: [
            "Europa și România — elemente geografice de bază",
            "România și Uniunea Europeană",
            "Europa și Uniunea Europeană în lumea contemporană",
          ],
        },
        {
          id: "filosofie",
          nume: "Filosofie",
          sursa_nume: "Filosofie",
          in_reforma: true,
          regulament_ref: "liceu/clasa-12/filosofie",
          capitole: [
            "Omul",
            "Morala",
            "Politica",
            "Cunoașterea",
            "Existența",
            "Filosofia",
          ],
        },
      ],
    },
  ],
};

export default liceu;
