import DOMPurify from "dompurify";

// Allowed SVG tags for geometric figures generated by Gemini OCR
const SVG_TAGS = [
  "svg",
  "g",
  "path",
  "circle",
  "ellipse",
  "rect",
  "line",
  "polyline",
  "polygon",
  "text",
  "tspan",
  "defs",
  "marker",
  "symbol",
  "use",
  "linearGradient",
  "radialGradient",
  "stop",
  "clipPath",
  "mask",
  "pattern",
  "image",
  "foreignObject",
  "title",
  "desc",
  "animate",
  "animateTransform",
  "animateMotion",
  "set",
];

// Allowed SVG attributes — no event handlers (on*), no javascript: URIs
const SVG_ATTRS = [
  "id",
  "class",
  "style",
  "transform",
  "d",
  "fill",
  "stroke",
  "stroke-width",
  "stroke-dasharray",
  "stroke-linecap",
  "stroke-linejoin",
  "opacity",
  "visibility",
  "display",
  "clip-path",
  "mask",
  "cx",
  "cy",
  "r",
  "rx",
  "ry",
  "x",
  "y",
  "x1",
  "y1",
  "x2",
  "y2",
  "width",
  "height",
  "viewBox",
  "preserveAspectRatio",
  "xmlns",
  "points",
  "marker-end",
  "marker-start",
  "marker-mid",
  "refX",
  "refY",
  "markerWidth",
  "markerHeight",
  "orient",
  "text-anchor",
  "dominant-baseline",
  "font-size",
  "font-family",
  "font-weight",
  "font-style",
  "letter-spacing",
  "dy",
  "gradientUnits",
  "gradientTransform",
  "spreadMethod",
  "offset",
  "stop-color",
  "stop-opacity",
  "href",
  "xlink:href",
  "dur",
  "repeatCount",
  "from",
  "to",
  "by",
  "values",
  "keyTimes",
  "attributeName",
  "attributeType",
  "begin",
  "end",
];

// L-security (audit 2026-07-09): `<image>`/`<use>` need `href`/`xlink:href` for
// LEGITIMATE internal refs (`#defs-id`) and embedded raster (`data:image/...`),
// but DOMPurify's default URI check also allows external `http(s)://` there —
// an OCR'd SVG figure could load a remote tracking pixel. Scoped to just these
// two tags (NOT a global ALLOWED_URI_REGEXP override, which would also break
// ordinary `<a href="https://...">` links elsewhere in sanitized content).
// Registered once at module load — DOMPurify hooks are additive per call.
let hooksRegistered = false;
function registerHrefGuard(purify: typeof DOMPurify) {
  if (hooksRegistered) return;
  hooksRegistered = true;
  purify.addHook("afterSanitizeAttributes", (node) => {
    const tag = node.tagName?.toLowerCase();
    if (tag !== "image" && tag !== "use") return;
    for (const attr of ["href", "xlink:href"]) {
      const val = node.getAttribute(attr);
      if (val && !/^(#|data:image\/)/i.test(val)) {
        node.removeAttribute(attr);
      }
    }
  });
}

export function sanitizeHtml(html: string): string {
  if (typeof window === "undefined") return html;
  registerHrefGuard(DOMPurify);
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true, svg: true, mathMl: true },
    ADD_TAGS: SVG_TAGS,
    ADD_ATTR: SVG_ATTRS,
    // Block dangerous patterns explicitly
    FORBID_ATTR: [
      "onerror",
      "onload",
      "onclick",
      "onmouseover",
      "onfocus",
      "onblur",
      "onchange",
      "onsubmit",
      "onkeydown",
      "onkeyup",
    ],
    FORCE_BODY: false,
    ALLOW_DATA_ATTR: false,
  });
}
